version: '3'

services:
  coin-api:
    container_name: coin-api
    build:
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - '3000:3000'
    restart: 'on-failure'
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
